[metadata]
name = gpspublisher
authors = Harpia Harpyja
author_email = henrique@harpia.tec.br
description = Read and publish gps data from a device
platforms = linux, win32
; classifiers =
;     Programming Language :: Python :: 3.8


[options]
zip_safe = False
package_dir=
    =src
include_package_data = True
packages = find:
; python_requires = >=3.7
; install_requires =
;     clrprint

[options.packages.find]
where=src

[options.extras_require]
testing =
    pytest>=6.0
    pytest-cov>=2.0
    mypy>=0.910
    flake8>=3.9
    tox>=3.24

[flake8]
max-line-length = 160